import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import Footer from './components/Footer/Footer';
import Header from './components/Header/Header';
import Sidebar from './components/Sidebar/Sidebar';
import './globals.css';
import styles from './layout.module.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const font_Noto_Sans_KR = Noto_Sans_KR({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin']
});

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={font_Noto_Sans_KR.className}>
				<div className={styles.wrapper}>
					<Header className={styles.header} />
					<Sidebar className={styles.sidebar} />
					<div className={styles.body}>{children}</div>
					<Footer className={styles.footer} />
				</div>
			</body>
		</html>
	);
}
